# Generated by Django 5.2 on 2025-04-08 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Logo', models.ImageField(blank=True, null=True, upload_to='airline_logos/')),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flight_number', models.CharField(max_length=10, unique=True)),
                ('Departure_time', models.DateTimeField()),
                ('Arrival_time', models.DateTimeField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Seat_available', models.PositiveBigIntegerField()),
                ('Airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Flight_from_Airline', to='flight.airline')),
                ('Destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Flight_to_destination', to='flight.airline')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_date', models.DateTimeField(auto_now_add=True)),
                ('Booking_status', models.CharField(choices=[('CONFIRMED', 'confirmed'), ('CANCELLED', 'cancelled'), ('PENDING', 'pending')], default='PENDING', max_length=10)),
                ('Flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Booking', to='flight.flight')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Payment_date', models.DateTimeField(auto_now_add=True)),
                ('Payment_status', models.CharField(choices=[('PAID', 'paid'), ('FAILED', 'failed'), ('PENDING', 'pending')], default='PENDING', max_length=10)),
                ('Booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payment', to='flight.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seat_number', models.CharField(max_length=5)),
                ('Is_booking', models.BooleanField(default=False)),
                ('Flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Seat', to='flight.flight')),
            ],
        ),
    ]
